set(HAS_RAJA OFF)
set(HAS_RAJA_CUDA OFF)
find_package(RAJA QUIET)
if(TARGET RAJA)
  message(STATUS "Found RAJA")
  set(HAS_RAJA ON)
  add_library(raja-tpl INTERFACE)
  if(APPLE)
    set(CMAKE_THREAD_LIBS_INIT "-lpthread")
    set(CMAKE_HAVE_THREADS_LIBRARY 1)
    set(CMAKE_USE_WIN32_THREADS_INIT 0)
    set(CMAKE_USE_PTHREADS_INIT 1)
    set(THREADS_PREFER_PTHREAD_FLAG ON)
  else()
    find_package(Threads REQUIRED)
    target_link_libraries(raja-tpl INTERFACE Threads::Threads)
  endif()
  find_package(umpire REQUIRED)
  if(TARGET RAJA::cuda)
    set(HAS_RAJA_CUDA ON)
    message(STATUS "Found CUDA targets for RAJA")
    enable_language(CUDA)
  else()
    message(STATUS "Could not find CUDA targets for RAJA")
  endif()

  target_link_libraries(raja-tpl INTERFACE RAJA umpire mpi-tpl warnings)
else()
  message(STATUS "Could not find RAJA. " "RAJA examples will not be built.")
endif()
