include(CheckLanguage)
check_language(Fortran)
set(HAS_FORTRAN OFF)
if(CMAKE_Fortran_COMPILER)
  set(HAS_FORTRAN ON)
  enable_language(Fortran)
  message(STATUS "Found Fortran compiler")
  set(CMAKE_Fortran_MODULE_DIRECTORY ${PROJECT_BINARY_DIR}/include)
else()
  message(STATUS "Could not find Fortran compiler")
endif()
